sample:
  initialize: true
  firstNames:
    - Robert
    - DaShaun
    - Sean
  lastNames:
    - Sirchia
    - Carter
    - Noyes
  emails:
    - robertsi@magenic.com
    - dacarter@pivotal.io
    - snoyes@pivotal.io

security:
  basic:
    enabled: false

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
